doc/toolchain_setup: Add missing apt dependency
libhidapi-dev is required to build icestorm:
```
pi_pico_interface.c:5:10: fatal error: hidapi/hidapi.h: No such file
or directory
```

Tested with podman.

Signed-off-by: Marcello Sylvester Bauer <sylv@sylv.io>